language: php

os: linux

php:
    - 7.2
    - 7.3
    - 7.4

env:
    jobs:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS}

script:
    - vendor/bin/phpunit